import Head from "next/head";
import Experience from "../components/experience";
import Project from "../components/project";
import Skills from "../components/skills";
import Education from "../components/education";
import ContactMe from "../components/contactMe";
import Main from "../components/main";
import NavBar from "../components/navBarSide";

export default function Home() {
  return (
    <div>
      <NavBar />
      <Head>
        <meta property="og:image" content="/arLogo.png" />
        <title>AR Software Developer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="  px-10 pb-20 bg-slate-100 dark:bg-gray-900 md:px-20 lg:px-40">
        <Main />
        <Skills />
        <Experience />
        <Education />
        <Project />
        <ContactMe />
        <div className="mx-auto flex justify-center">V1.0</div>
      </main>
    </div>
  );
}
